FROM golang:1.19-alpine3.16
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -o /bin/app ./turn

FROM alpine
WORKDIR /src

COPY --from=0 /bin/app /bin/app

ENTRYPOINT ["/bin/app"]