version: '3.8'

services:
  server:
    image: dylanhuang399/goroom
    environment:
       - ENVIRONMENT=PRODUCTION
       - CERT=/etc/nginx/ssl/sslbundle.crt
       - KEY=/etc/nginx/ssl/private.key
    deploy:
      replicas: 1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    ports:
      - 8080:8080
    volumes:
      - /etc/nginx/ssl/sslbundle.crt:/etc/nginx/ssl/sslbundle.crt
      - /etc/nginx/ssl/private.key:/etc/nginx/ssl/private.key
    command: --addr :8080
  turn:
    image: dylanhuang399/goturn
    deploy:
      replicas: 1
    restart: always
    ports:
      - 3478:3478
    # command: --public-ip 127.0.0.1 --port 3478